# Generated by Django 4.2.23 on 2025-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_producto_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='despachado',
            field=models.BooleanField(default=False),
        ),
    ]
