# Generated by Django 4.2.23 on 2026-09-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_producto_despachado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impreso',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='recogido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='recogido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
